version: '3'
services:

  web:
    build: .
    container_name: machinelearning
    ports:
      - '8888:8888'
    volumes:
      - jupyter_store:/home/jupyter

volumes:
  jupyter_store:

networks:
  default:
    driver: bridge
